SELECT @max_id := IFNULL(MAX(id), 0) FROM programas;
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Cocina', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Cocina.', '', '/uploads/programas/legacy_1779700552229_fsdth.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Programa Especial', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Programa Especial.', '', '/uploads/programas/legacy_1779700552731_49hs9.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Entretenimiento', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Entretenimiento.', '', '/uploads/programas/legacy_1779700552890_2r34q.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Documental', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Documental.', '', '/uploads/programas/legacy_1779700552998_ohlz0.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Mosaico', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Mosaico.', '', '/uploads/programas/legacy_1779700553105_hgcvu.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Cultura', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Cultura.', '', '/uploads/programas/legacy_1779700553208_ld6cz.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Salud', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Salud.', '', '/uploads/programas/legacy_1779700553323_m9j1b.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Ecosistemas', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Ecosistemas.', '', '/uploads/programas/legacy_1779700553425_v3zma.jpg', 'TV', 'Canal 10', 1, '[]');
SET @max_id = @max_id + 1;
INSERT INTO programas (id, nombre, conductor, horario, descripcion, descripcionLarga, imagen, tipo, estacion, activo, embeds) VALUES (@max_id, 'Entrevistas', 'Canal 10', 'Consultar Cartelera', 'Programa recuperado del archivo histórico del Canal 10. Entrevistas.', '', '/uploads/programas/legacy_1779700553522_qsyf3.jpg', 'TV', 'Canal 10', 1, '[]');
